var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                o                   xx      xx                  ",
   "                  o            xxx           xx                                 ",
   "                  x!!!x                     xx                    xxx           ",
   "                  xxvxx x          xxxxx                         x!!!x          ",
   " x!x                                                             xvvvx      x!x ",
   "  x                        xx             o                 o                x  ",
   "  x                         xx                             xx                x  ",
   "  x          xxxx                        xxxxx                             o x  ",
   "  x          x  x       o       xxx                                          x  ",
   "  x  @       x  x                                                 xxx        x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx                            xxxxxxxx xxxxxxxxxx  ",
   "                              x                            x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         xxxx     x!   !x                                                     ",
   "                                              xx  x!   !x                                                     ",
   "                 o                                x!   !x                                                     ",
   "                xxx   x   xxx     xxx             x!   !x                                                     ",
   "                x!!!!!!!!!!!x                     x!   !x                                                     ",
   "                xxvxxxvxxxvxx            xxxxx    x!   !x                                                     ",
   "                                                  x!   !x                      o                              ",
   "                                                  x!   !x                      x                              ",
   "                             o        xxx         x!   !x                  x       x                          ",
   "                                  xx              x!   !x               x             x                       ",
   "         xxx    xxxxxxxxxxxxxxx                   x!   !x                                                     ",
   "                                                  x!   !x         x=    =    = o =    =    =x                 ",
   "                                                  x!   !x         xxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "                                                  x!   !x                                                     ",
   "      xx                                          x!   !x    xxx                                              ",
   "       xxxx                                        v   v                                                      ",
   "                                                                 x!!!!!!!!!!!!!!!!!!!!!!!!!x                  ",
   " x!x          xxx                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x!x    ",
   "  x                    x                        x              x                             x          x     ",
   "  x  @                 x                        x     o       x                               x      o  x     ",
   "  xxxxxxxxxxxxxxxxxxxxxx                        xxxxxxxxxxxxxxx                               xxxxxxxxxxx     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                               xxxxxxxxxxxxxxx                                           ",
   "    xx                   o                     xvv    v     vvx                                          ",
   "    x=                   x                                o                                              ",
   "    x                                                     xx                                             ",
   "    x=             x                                                                                     ",
   "    x                         x                                                                          ",
   "    x=                              x                                                                    ",
   "    x                                                    xx                                              ",
   "    x=                   x                o                                                              ",
   "    x             o                       x      xxxx                                                    ",
   "    x=            x           x                                                                          ",
   "    x                                        xx                                                          ",
   "    x=                     x                                                                             ",
   "    x         x                    x                 xx                                                  ",
   "    x=                  x=             x             v                                                   ",
   "    x             x                                                                                      ",
   "    x=                           x                                                                       ",
   "    x                  x               o          o            o                                         ",
   "    x=                                 x         xxx          xxx                                        ",
   "    x            x                                                                                       ",
   "    x=                              x                   x                                                ",
   "    xx                x                                            o                                     ",
   "                                                                   x!! !!x                               ",
   "   x!x          xxx                                      xxx       x!! !!x                               ",
   "    x                     x!!!!!!!!!!x              o              x!! !!x                               ",
   "    x @                   xxxxxxxxxxxx             xx                                  x!x               ",
   "    xxxxxxxxx                        x                                                  x                ",
   "                      o     o     o  x         x             x                  o       x                ",
   "              xxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx                ",
   "                                                                                                         ",
   "                                                                                                         "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
